### ISSUE TITLE
deploy key not supported

### ISSUE THREAD

**Issue by trainingcity** [jmhardison/docker-moodle#34]
getting a warning on docker-compose up -d

WARNING: Some services (reinvent_dbapp, reinvent_moodleapp) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm

**Comment by jmhardison** [comment]
This was modeled for a stack deployment, which is what the warning is noting. What we can do is break this up into a couple deployment options, one being a dev/test that doesn't use deploy sections. But end of the day it's an issue when using it when not deployed against a swarm cluster.

So for some clarity, whats your desired environment with the compose file?

**Comment by jmhardison** [comment]
I'm going to go ahead and close this. The `deploy` key is properly ignored when not deployed against swarm, and it only adds the restart configuration and instance constraints.
